// person
export const PERSON_GET_ALL_REQUESTED = 'PERSON_GET_ALL_REQUESTED';
export const PERSON_GET_ALL_SUCCEEDED = 'PERSON_GET_ALL_SUCCEEDED';
export const PERSON_GET_ALL_FAILED = 'PERSON_GET_ALL_FAILED';

export const PERSON_ADD_REQUESTED = 'PERSON_ADD_REQUESTED';
export const PERSON_ADD_SUCCEEDED = 'PERSON_ADD_SUCCEEDED';
export const PERSON_ADD_FAILED = 'PERSON_ADD_FAILED';

export const PERSON_REMOVE = 'PERSON_REMOVE';

export const PERSON_UPDATE_REQUESTED = 'PERSON_UPDATE_REQUESTED';
export const PERSON_UPDATE_SUCCEEDED = 'PERSON_UPDATE_SUCCEEDED';
export const PERSON_UPDATE_FAILED = 'PERSON_UPDATE_FAILED';

export const PERSON_SELECT = 'PERSON_SELECT';
export const PERSON_UNSELECT = 'PERSON_UNSELECT';


// modal
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

